### ISSUE TITLE
In your implementation of Mean teacher, isn't the student model and the teacher model the same?

### ISSUE THREAD

**Issue by hzhz2020** [google-research/mixmatch#45] opened 2022-02-21 02:28 UTC
In the Mean Teacher paper, teacher model weights are EMA of student model's weights. In your implementation of Mean Teacher is the student model and teacher model have exactly the same weights?

**Comment by carlini** [comment] 2022-02-21 02:57
Closing this issue as a duplicate of https://github.com/google-research/fixmatch/issues/74. We can re-open it if it turns out it's an actual issue.

**Closed as completed by carlini** 2022-02-21 02:57 UTC
